# Generated by Django 4.2.14 on 2024-07-19 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitcherapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cook',
            options={'ordering': ('job_title',)},
        ),
        migrations.AlterField(
            model_name='dishtype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
