# Generated by Django 4.2.14 on 2024-07-19 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitcherapp', '0003_alter_cook_groups_alter_cook_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cook',
            name='year_of_experience',
            field=models.IntegerField(default=0),
        ),
    ]
