# Generated by Django 4.2.14 on 2024-07-20 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitcherapp', '0004_alter_cook_year_of_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ('dish_type',)},
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(related_name='dishes', to='kitcherapp.ingredient'),
        ),
    ]
