# Generated by Django 4.2.14 on 2024-07-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitcherapp', '0005_ingredient_alter_dish_options_dish_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='dishes', to='kitcherapp.ingredient'),
        ),
    ]
